name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    name: Lint, type-check, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Enforce formatting (Black + Ruff fix)
        run: |
          make fmt

      - name: Lint (Ruff)
        run: |
          ruff check --output-format=github src tests

      - name: Type check (mypy)
        run: |
          mypy --ignore-missing-imports src tests

      - name: Run tests (pytest)
        run: |
          pytest -q

  build-docker:
    name: Build Docker image
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image (if Dockerfile exists)
        run: |
          if [ -f Dockerfile ]; then
            docker build . -t ibkr-options-bot:ci;
          else
            echo "No Dockerfile found, skipping image build.";
          fi
